# based on recipe by Carsten Ehbrecht
# https://binstar.org/PinguCarsti

package:
    name: grib_api
    version: 1.12.1

source:
    fn: grib_api-1.12.1.tar.gz
    url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.12.1.tar.gz?api=v2
    md5: d9a90daa94766617831cf37ccac1e296 

requirements:
    build:
        - python
        - numpy
        - jasper
        - libnetcdf

build:
    number: 0

about:
    home: https://software.ecmwf.int/wiki/display/GRIB/Home
    license: Apache License v2.0
