package:
  name: pyglpk
  version: 0.3

source:
  fn: pyglpk-0.3.tar.bz2
  url: http://tfinley.net/software/pyglpk/pyglpk-0.3.tar.bz2

  patches:
    - patch.diff

requirements:
  build:
    - python

test:
  imports:
    - glpk

about:
  home: http://tfinley.net/software/pyglpk/
  license: GPL
