package:
  name: pyproj
  version: 1.9.3

source:
  fn: pyproj-1.9.3.tar.gz
  url: http://pyproj.googlecode.com/files/pyproj-1.9.3.tar.gz

requirements:
  build:
    - python

about:
  home: http://code.google.com/p/pyproj/
  license: MIT

