package:
    name: cvxopt_glpk
    version: 1.1.6

source:
    git_url: https://github.com/cvxopt/cvxopt.git
    git_tag: 1.1.6

    patches:
      - setup.py.diff

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python

test:
    imports:
        - cvxopt
        - cvxopt.misc

about:
    home: http://cvxopt.org/
    license: GPL v3
