package:
  name: line_profiler
  version: 1.0b3

source:
  fn: line_profiler-1.0b3.tar.gz
  url: https://pypi.python.org/packages/source/l/line_profiler/line_profiler-1.0b3.tar.gz
  md5: 63fc2a757192eb5e577559cfdff5b831

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - line_profiler

  commands:
    - kernprof.py  --help

about:
  home: http://packages.python.org/line_profiler
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
