package:
    name: trmm_rsl
    version: 1.47

source:
    fn: rsl.v1.47.tar.gz
    url: ftp://trmm-fc.gsfc.nasa.gov/software/rsl-v1.47.tar.gz

    patches:
        - patch.diff
build:
    number: 2

about:
    home: http://trmm-fc.gsfc.nasa.gov/trmm_gv/software/rsl/
    license: LGPL
